file(REMOVE_RECURSE "${TEST_ROOT}")
set(INSTALL_PREFIX "${TEST_ROOT}/install")
set(CONSUMER_BUILD_DIR "${TEST_ROOT}/build")

execute_process(
    COMMAND "${CMAKE_COMMAND}" --install "${PROJECT_BUILD_DIR}" --prefix "${INSTALL_PREFIX}"
    RESULT_VARIABLE INSTALL_RESULT
    OUTPUT_VARIABLE INSTALL_OUTPUT
    ERROR_VARIABLE INSTALL_ERROR
)
if(NOT INSTALL_RESULT EQUAL 0)
    message(FATAL_ERROR "nats_asio install failed:\n${INSTALL_OUTPUT}\n${INSTALL_ERROR}")
endif()

set(CONFIGURE_COMMAND
    "${CMAKE_COMMAND}"
    -S "${CONSUMER_SOURCE_DIR}"
    -B "${CONSUMER_BUILD_DIR}"
    "-Dnats_asio_DIR=${INSTALL_PREFIX}/${INSTALL_CMAKE_DIR}"
)
if(NOT DEPENDENCY_PREFIX STREQUAL "")
    list(APPEND CONFIGURE_COMMAND "-DCMAKE_PREFIX_PATH=${DEPENDENCY_PREFIX}")
endif()

execute_process(
    COMMAND ${CONFIGURE_COMMAND}
    RESULT_VARIABLE CONFIGURE_RESULT
    OUTPUT_VARIABLE CONFIGURE_OUTPUT
    ERROR_VARIABLE CONFIGURE_ERROR
)
if(NOT CONFIGURE_RESULT EQUAL 0)
    message(FATAL_ERROR
        "Installed-package consumer configure failed:\n${CONFIGURE_OUTPUT}\n${CONFIGURE_ERROR}")
endif()

execute_process(
    COMMAND "${CMAKE_COMMAND}" --build "${CONSUMER_BUILD_DIR}"
    RESULT_VARIABLE BUILD_RESULT
    OUTPUT_VARIABLE BUILD_OUTPUT
    ERROR_VARIABLE BUILD_ERROR
)
if(NOT BUILD_RESULT EQUAL 0)
    message(FATAL_ERROR
        "Installed-package consumer build failed:\n${BUILD_OUTPUT}\n${BUILD_ERROR}")
endif()
